"""empty message

Revision ID: 4b496516864c
Revises: 27774adff609
Create Date: 2022-08-06 17:51:51.552847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b496516864c'
down_revision = '27774adff609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carta_aval', sa.Column('fecha_a_pedir', sa.Integer(), nullable=False))
    op.add_column('carta_aval', sa.Column('fecha_solicitada', sa.DateTime(), nullable=False))
    op.drop_column('carta_aval', 'fecha')
    op.add_column('clave', sa.Column('fecha_solicitada', sa.DateTime(), nullable=False))
    op.drop_column('clave', 'fecha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clave', sa.Column('fecha', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('clave', 'fecha_solicitada')
    op.add_column('carta_aval', sa.Column('fecha', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('carta_aval', 'fecha_solicitada')
    op.drop_column('carta_aval', 'fecha_a_pedir')
    # ### end Alembic commands ###
