"""empty message

Revision ID: 52c6d4ea05c8
Revises: e6f661cb7d22
Create Date: 2022-08-05 15:41:21.494284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c6d4ea05c8'
down_revision = 'e6f661cb7d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('razon', sa.String(length=600), nullable=False),
    sa.Column('lugar', sa.String(length=80), nullable=False),
    sa.Column('fecha', sa.Integer(), nullable=False),
    sa.Column('poliza', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('carta_aval', sa.Column('poliza', sa.Integer(), nullable=False))
    op.alter_column('carta_aval', 'uso_personal',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carta_aval', 'uso_personal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('carta_aval', 'poliza')
    op.drop_table('clave')
    # ### end Alembic commands ###
