"""empty message

Revision ID: 553cb9f6621e
Revises: 2c211aa75469
Create Date: 2022-07-25 22:53:21.795590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553cb9f6621e'
down_revision = '2c211aa75469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###
