"""empty message

Revision ID: 59eaa4d697ee
Revises: cf4a0286c46a
Create Date: 2022-08-04 16:23:35.060546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59eaa4d697ee'
down_revision = 'cf4a0286c46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carta_aval', sa.Column('fecha', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carta_aval', 'fecha')
    # ### end Alembic commands ###
