"""empty message

Revision ID: 68bf02e8c967
Revises: 553cb9f6621e
Create Date: 2022-07-27 04:40:36.302311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bf02e8c967'
down_revision = '553cb9f6621e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cedula', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('poliza', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'poliza')
    op.drop_column('user', 'cedula')
    # ### end Alembic commands ###
