"""empty message

Revision ID: 7dd156d5a75d
Revises: 0559bcf7ded0
Create Date: 2022-08-12 03:19:14.638235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd156d5a75d'
down_revision = '0559bcf7ded0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carta_aval', 'lugar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carta_aval', sa.Column('lugar', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
