"""empty message

Revision ID: b11b77959c7f
Revises: 5b9cca831a44
Create Date: 2022-08-05 23:01:53.639098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11b77959c7f'
down_revision = '5b9cca831a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clave', 'fecha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clave', sa.Column('fecha', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
