"""empty message

Revision ID: cf4a0286c46a
Revises: d9df684b3574
Create Date: 2022-08-03 23:04:36.816830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4a0286c46a'
down_revision = 'd9df684b3574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carta_aval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=600), nullable=False),
    sa.Column('lugar', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carta_aval')
    # ### end Alembic commands ###
