"""empty message

Revision ID: d5d21c7b8075
Revises: 741a55cd55e5
Create Date: 2022-07-23 16:23:12.249173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d21c7b8075'
down_revision = '741a55cd55e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apellido', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('nombre', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nombre')
    op.drop_column('user', 'apellido')
    # ### end Alembic commands ###
