"""empty message

Revision ID: e6f661cb7d22
Revises: 59eaa4d697ee
Create Date: 2022-08-04 23:22:38.849050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f661cb7d22'
down_revision = '59eaa4d697ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carta_aval', sa.Column('uso_personal', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carta_aval', 'uso_personal')
    # ### end Alembic commands ###
